// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnirN7SKOQkzJaHnZ5IlVEFxp53tJ4ghs',
    appId: '1:5834464387:web:49c13fdeff6644a69e0fb6',
    messagingSenderId: '5834464387',
    projectId: 'travel-app-distribution',
    authDomain: 'travel-app-distribution.firebaseapp.com',
    storageBucket: 'travel-app-distribution.appspot.com',
    measurementId: 'G-C72N6FLWHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHNyRa_wpmPpZxU922vP73-3jC7pNB8Kg',
    appId: '1:5834464387:android:1b206ac1e7ca04889e0fb6',
    messagingSenderId: '5834464387',
    projectId: 'travel-app-distribution',
    storageBucket: 'travel-app-distribution.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ExmU5bO8hUb7XxrB_wAg7bfG7ejjCLg',
    appId: '1:5834464387:ios:9bf323ab904517f19e0fb6',
    messagingSenderId: '5834464387',
    projectId: 'travel-app-distribution',
    storageBucket: 'travel-app-distribution.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );
}
